image: alpine

variables:
  PROJECT_NAMESPACE: "${CI_PROJECT_NAMESPACE}"
  PROJECT_NAME: "bmbl"


include:
  - project: 'idobits/ci-cd-tools'
    ref: 'master'
    file: 'ci-cd-tools.yml'

stages:
 - test
 - build
 - deploy


build image:
  extends: .buildImage
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:latest
    DOCKER_FILE: 'docker/Dockerfile'
  stage: build
  before_script:
    - cp $ENV_FILE .env
  only:
    - master

build image production:
  extends: .buildImage
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    DOCKER_FILE: 'docker/Dockerfile'
  stage: build
  before_script:
    - cp $ENV_FILE .env
  only:
    - tags




# Push the image to Docker Swarm as service and run a rolling deploy
deploy production:
  extends: .deploy
  stage: deploy
  variables:
    IMAGE_BASE: ${CI_REGISTRY_IMAGE}
    IMAGE_TAG: ${CI_COMMIT_TAG}
  dependencies: []
  environment:
    name: discord-bumblebee-fm
  only:
    - tags
