image: alpine

include:
  - project: 'idobits/ci-cd-tools'
    ref: 'master'
    file: 'ci-cd-tools.yml'


stages:
 - test
 - build
 - deploy


build image:
  extends: .build_job
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG:=latest}
    DOCKER_FILE: 'docker/Dockerfile'
  stage: build
  before_script:
    - cp $ENV_FILE .env
    - echo $IMAGE_NAME
    - echo $CI_COMMIT_TAG
    - echo ${CI_COMMIT_TAG:=latest}
  only:
    - master
    - tags

# Push the image to Docker Swarm as service and run a rolling deploy
deploy production:
  extends: .deploy
  stage: deploy
  variables:
    PROJECT_NAMESPACE: "${CI_PROJECT_NAMESPACE}"
    PROJECT_NAME: "gdg"
    IMAGE_BASE: ${CI_REGISTRY_IMAGE}
    IMAGE_TAG: ${CI_COMMIT_TAG:=latest}
  dependencies: []
  environment:
    name: discord-bumblebee-fm
  only:
    - tags
