version: '3.7'

services:
    discord:
        image: ${IMAGE_BASE}:${IMAGE_TAG}
        environment:
            - NODE_ENV=production
            - LOG_INFO=info
        deploy:
            restart_policy:
                delay: 30s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
