version: '3.6'
services:
    discord:
        build: 
            context: ./
            dockerfile: docker/Dockerfile
            args:
                - NPM_GLOBAL_PACKAGES=nodemon typescript
                - BUILD_PROD=false
        volumes:
            - .:/var/www/html
            - ./node_modules:/var/www/html/node_modules:delegated
        environment:
            - NODE_ENV=production
        container_name: "discord"
        # networks:
        #   - api_bumblebee-net

# networks:
#   api_bumblebee-net:
#     external: true
