version: '3.6'
services:
    discord:
        image: ${CI_REGISTRY}/bumblebee/discord:latest
        environment:
            - NODE_ENV=production
            - LOG_INFO=info
        deploy:
            restart_policy:
                condition: any
                delay: 10s
                max_attempts: 3
                window: 120s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
