version: '3.6'

services:
    discord:
        image: ${DISCORD_IMAGE}
        environment:
            - NODE_ENV=production
            - LOG_INFO=info
        deploy:
            restart_policy:
                condition: any
                delay: 15s
                max_attempts: 60
                window: 30s
            replicas: 1
            update_config:
                parallelism: 2
                delay: 10s
