version: '3.8'
services:
    discord:
        build: 
            context: ./
            dockerfile: docker/Dockerfile
            args:
                - NPM_GLOBAL_PACKAGES=nodemon typescript
                - BUILD_PROD=true
        # volumes:
        #     - .:/var/www/html
        #     - ./node_modules:/var/www/html/node_modules:delegated
        environment:
            - NODE_ENV=development
        container_name: "discord"
        networks:
          - bumblebee-net

networks:
    bumblebee-net:
        external: true
